### ISSUE TITLE
modify content

### ISSUE THREAD

**Issue by georgkrause** [msva/lua-htmlparser#38]
Is there any way to modify the content of a html node? A function like setText() would be great!

**Comment by msva** [comment]
Actually, it is not that hard to implement that by yourself, but, let's see. Maybe there will be something like that in the future :)

**Comment by Freed-Wu** [comment]
It is incorrect. gettext() will get node's text, so settext should also set node's text.
However,

```lua
function ElementNode:settext(c)
	self.root._text=c
end
```

It is set root node's text. the correct implementation should be like:

```lua
function ElementNode:settext(c)
  local old_c = self:gettext()
  self.root._text = self.root._text:sub(1, self._openstart - 1) .. c .. self.root._text:sub(self._closeend + 1)
  local diff = #c - #old_c
  for _, node in ipairs(self.root:select "*") do
    -- invalid node
    if self._openstart < node._openstart and node._closeend < self._closeend then
      node = nil
    elseif node._closeend >= self._closeend then
      node._closeend = node._closeend + diff
      if node._openstart >= self._closeend then
        node._openstart = node._openstart + diff
      end
    end
  end
end
```

**Comment by msva** [comment]
@Freed-Wu wouldn't you want to open a PR with your suggested changes (for example, to claim authorship of the modifications)?

**Comment by msva** [comment]
and if so, can you take #68 in account, please?

Or... wouldn't merging it breaks the things you wanted to use this library for?
