### ISSUE TITLE
problem with htmlparser.ElementNode

### ISSUE THREAD

**Issue by siyanew** [msva/lua-htmlparser#39]
when i run my script this error shown : 
>error loading module 'htmlparser.ElementNode' from file '.luarocks/share/lua/5.2/htmlparser/ElementNode.lua':
>        .luarocks/share/lua/5.2/htmlparser/ElementNode.lua:141: '=' expected near 'nextpart'

**Comment by msva** [comment]
are you sure, you running it with lua5.2, but not 5.1? It looks like your lua don't know about goto.
Anyway, scm-0 version (uploaded to luarocks) has some fixes to avoid goto, so, check it out and comment, if bug still appears.
