### ISSUE TITLE
deadloop when attribute has <> char

### ISSUE THREAD

**Issue by RelicOfTesla** [msva/lua-htmlparser#42]
``` lua
htmlparser.parse([[
<div data-pic="aa<%=image_url%>bb" ></div>
]])
print('ok')
```

Lua 5.1.5 / Lua 5.3.2
not print "ok", deadlock!!

**Comment by msva** [comment]
Hi!
Sorry for ignoring the issue for year.
Unfortunatelly github didn't send me notifications about new issues after previous maintainer rerooted the repo.
It looks like it was he, who get all those emails.

I'll try to handle all the issues in the near time.

**Comment by msva** [comment]
Actually, it is not intended to use this module with templaters (looks like something ruby'ish, or, maybe, moonscript?).
And if you anyway want to do that, it is intended that you'll take care of template strings before passing it to the parser (here should be reminder why HTML parsing is bad).
But I'll try to add special condition for that, to not deadloop.
