### ISSUE TITLE
Couldn't Install via LuaRocks

### ISSUE THREAD

**Issue by darmie** [msva/lua-htmlparser#43]
I tried installing htmlparser via luarocks `luarocks install htmlparser` I got the following error:

`Error: No results matching query were found.`

**Comment by Guard13007** [comment]
Check the version of Lua / LuaRocks you're using and what this library supports. Also, note that for some reason the rockspec for compatibility with LuaJIT isn't uploaded (if you were trying to use that).

Are you still having this problem?

**Comment by msva** [comment]
Hi!
Sorry for ignoring the issue for about a year.
Unfortunatelly github didn't send me notifications about new issues after previous maintainer rerooted the repo.
It looks like it was he, who get all those emails.

I'll try to handle all the issues in the near time.

**Comment by msva** [comment]
THis issue will be automatically fixed when LuaRocks guys will fix https://github.com/luarocks/luarocks-site/issues/107
