### ISSUE TITLE
I  find a big bug,hope you update ,thank you! 

### ISSUE THREAD

**Issue by hongzhewudi** [msva/lua-htmlparser#45]
![image](https://cloud.githubusercontent.com/assets/9473584/23600218/58471e04-0280-11e7-8634-49391f6a45bd.png)
我不会讲英文，我的水品太差了，大概的说明了问题，谢谢！look picture

**Comment by wscherphof** [comment]
How to reproduce the issue?

**Comment by msva** [comment]
@hongzhewudi ping?

**Comment by msva** [comment]
@hongzhewudi 
1) as far as Google translated your chinese, you said that your english is bad. But, trust me, our chinese is much more bad 😎 
2) looks like you using outdated version. Could you try the version from git HEAD?

**Comment by boston2029** [comment]
> 1. as far as Google translated your chinese, you said that your english is bad. But, trust me, our chinese is much worse 😎

agree lol
