### ISSUE TITLE
Unable to install with luarocks

### ISSUE THREAD

**Issue by italomaia** [msva/lua-htmlparser#52]
Tried to install it and got the following error:

> luarocks install htmlparser --local

Error: Couldn't extract archive lua-htmlparser: unrecognized filename extension

**Comment by zja711** [comment]
i solved it by
>  # git clone https://github.com/msva/lua-htmlparser.git
> # cd lua-htmlparser/
> # luarocks make

**Comment by zja711** [comment]
i solved it by
`# git clone https://github.com/msva/lua-htmlparser.git
# cd lua-htmlparser/
# luarocks make`

**Comment by AffableZonkey** [comment]
I can't get this to install on Fedora27 via luarocks install or luarocks make. I get the unrecognized filename extension error when trying to install.

**Comment by Guard13007** [comment]
Same issue, same solution. :/

**Comment by Prasanna-sr** [comment]
same issue

**Comment by italomaia** [comment]
Ok, we have a workaround. Would a fix to the rock be viable?

**Comment by msva** [comment]
Fixed now
