### ISSUE TITLE
Bug: nil index error if parent child selector + any voidelement

### ISSUE THREAD

**Issue by keiviv** [msva/lua-htmlparser#55]
Hi @msva, huge thanks for your parser! Found a small, but annoying bug. 

#### Bug Description
Any tag listed in ````voidelements.lua```` casues the "_Attempt to index a nil value_" error if using a parent child selector.

#### Bug Reproduction
Shortest working example:
````lua
local htmlparser = require 'htmlparser'
local html = [[
<br><!-- ← This single tag causes nil index error. No error without it. -->
<div class="parent">
   <div class="child">msva rulit, kogda ne spit!</div>
</div>
]]
local root = htmlparser.parse(html)
local bug = root('.parent .child') -- Error only if a pair. No error if single.
print(bug[1]:getcontent())
````

#### Temp Workaround
Until fixed, remove all unpaired tags that are listed in ````voidelements.lua```` from the html to be processed:
````lua
html = html:gsub('<br>', ''):gsub('<br />', ''):gsub('<hr>', ''):gsub('etc', '')
````

**Comment by boston2029** [comment]
That's weird.

**Comment by msva** [comment]
@keiviv Hi there! Sorry for delay. It should be fixed now.

@boston2029 What exactly?
