### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by boston2029** [msva/lua-htmlparser#56]
How do I use this in Roblox because it'd be cool for displaying websites in Roblox.

**Comment by msva** [comment]
Well, I didn't touch roblox for an eternity already, so I didn't even remember if there is a lua-interpreter in the first place.
But even if it is, I'm pretty sure, this library is not what you want.
It's purpose is to convert HTML-code to the DOM-tree, get an element you need with selectors, and get it's content.
With additinal skill, it can be used to edit the DOM tree properly (and not just `gsub`'ing).

But it has nothing to do with either:
- fetching website source (you can use another library I maintain, [Lua-cURL](https://github.com/Lua-cURL/Lua-cURLv3/) for that)
- rendering the HTML-code to teh corresponding graphic interpretation (actually, it is so hard hat chrome's source takes few gigabytes)
- displaying rendered result (here you'll need some graphic libraries and using game's API)

**Comment by ChiliConSql** [comment]
When I try to run this code:
```
  fh = io.open("test.html", 'r')
  local root = html.parse(fh:read('*all'))
  fh:close()
````
I am getting the following error:

`[HTMLParser] [E] Main loop reached loop limit (1000). Consider either increasing it or checking HTML-code for syntax errors`

any ideas?
