### ISSUE TITLE
body is appearing as child of head in .nodes

### ISSUE THREAD

**Issue by minecraftcrush6** [msva/lua-htmlparser#60]
![Screenshot 2022-04-02 200904](https://user-images.githubusercontent.com/81498434/161406901-c4e2b7c0-82a8-46bb-a21b-1da1a472bf8f.png)
[Html file](https://cctwbt.samuellarsen.repl.co/index.html)
my code (before screenshot)
```lua
htmlparser = require("htmlparser")
file = fs.open("index.html")
root = htmlparser.parse(file.readAll())
```
Lua version: 5.1
(I feel I might be doing something wrong)

**Comment by msva** [comment]
please, add following code to your script (before calling `parse`):
```lua
htmlparser_opts = {
  debug = true
}
```

and call parser again. And upload the log (it will be very huge, so you can prefer to redirect output to file)

**Comment by msva** [comment]
Although, nevermind, I found the bug myself :)
